### ISSUE TITLE
Use CombatFlite as much as possible

### ISSUE THREAD

**Issue by abeardedbear** [132nd-vWing/VIS#1]
My suggestion is to convey as much possible information in the fewest amount of buckets as possible. Rather than creating documents, upon documents, and have people to follow them, we can use the CombatFlite files to draw contacts, write notes, and handle the intel from there. 

This could cover the idea of giving intel to all the pilots prior to a mission, and the FLs will have to get through that, because of the planning. 

If we don't have a very fancy way to do BDAs, we can make that also in CombatFlite. This is not ideal, by any means, but the guy collecting the Intel for the next mission, can import other layers, and upon that update the Intel master file

**Comment by 132ndNeck** [comment]
Very good and valid point. Combatflite will be used to maximum extent possible. However I think there will be need for some reports, but will streamline it better than we have had in OPUF.

**Comment by abeardedbear** [comment]
We could have a person - for the moment I volunteer on that, but could be anyone rotating in this role - getting all reports and draw them on CombatFlite

**Comment by 132ndNeck** [comment]
Yes, I plan on having 2 roles availeble if anyone would be interested for mission to mission
1. Intelligence (can be more than 1)
2. Commander Air Operations Centre. Deciding what missions that will be flown/tasked , and the ATO priorities. All based on the intelligence from last mission.

And most intel will be what we generate ourself.
