### ISSUE TITLE
BMP-2/3 images

### ISSUE THREAD

**Issue by 132ndLongShot** [132nd-vWing/VIS#2]
Mechanized BN:
The images of the BMP-2 and BMP-3 are swapped. BMP-2 looks like BMP-1 with a 30mm cannon and ATGM. BMP-3 is boxy with dual 100mm and 30mm cannon.

**Comment by 132ndNeck** [comment]
Good catch!
Thank you. Have fixed in the powerpoint, and will be part of next version.
